(function(M){var f=window.AmazonUIPageJS||window.P,r=f._namespace||f.attributeErrors,e=r?r("RetailSearchAutocompleteAssets"):f;e.guardFatal?e.guardFatal(M)(e,window):e.execute(function(){M(e,window)})})(function(M,f,r){f.$Nav.build("sx.iss.TemplateEngine",function(){var e={};return function d(a,b){var m=/^[a-zA-Z0-9_-]+$/.test(a)?e[a]=e[a]||d(document.getElementById(a).innerHTML):new Function("obj","var p=[],print=function(){p.push.apply(p,arguments);};with(obj){p.push('"+a.replace(/[\r\t\n]/g," ").replace(/'(?=[^#]*#>)/g,
"\t").split("'").join("\\'").split("\t").join("'").replace(/<#=(.+?)#>/g,"',$1,'").split("<#").join("');").split("#>").join("p.push('")+"');}return p.join('');");return b?m(b):m}});f.$Nav.when("sx.iss.DebugUtils","sx.iss.DomUtils").build("sx.iss.EventBus.instance",function(e,c){return new function(){function d(a){var b=typeof a,c="";"object"===b&&a.hasOwnProperty("name")?c=a.name:"string"===b&&(c=a);return c}var a={},b={};this.listen=function(b,h,f){var g,k="";if(c.isArray(b)){for(g=
0;g<b.length;g++)k=b[g],this.listen(k,h,f),e.logDebug("Listening for: "+k);return this}k=d(b);a[k]||(a[k]=[]);a[k].push({f:h,o:f});e.logDebug("Listening for: "+k);return this};this.trigger=function(b,c){var f=d(b);e.logDebugWithTrace("Trigger: "+f,c);var f=a[f],g;if(f){for(g=0;g<f.length;g++)f[g].f.call(f[g].o,c);return this}};this.triggerThrottledEvent=function(c,h,f){var g=d(c);e.logDebugWithTrace("Trigger (throttled): "+g,h);var k=a[g];c=b[g];if(k)return f===r&&(f=100),c&&(clearTimeout(c),delete b[g]),
c=setTimeout(function(){var a;for(a=0;a<k.length;a++)k[a].f.call(k[a].o,h);delete b[g]},f),b[g]=c,this}}});f.$Nav.when("sx.iss.DebugUtils","sx.iss.DomUtils").build("sx.iss.IssContext",function(e,c){var d,a,b=[];return{getFastlabs:function(){return a},setFastlabs:function(b){a=b},getTriggeredFastlabs:function(){return b},clearTriggeredFastlabs:function(){b=[]},addTriggeredFastlabs:function(a){b=b.concat(a)},getConfiguration:function(){return d},setConfiguration:function(a){d=a}}});
f.$Nav.build("sx.iss.suggestionUtils",function(){var e=/\s/;return{getPrefixPos:function(c,d){return c.toLowerCase().indexOf(d.toLowerCase())},getPrefixPosMultiWord:function(c,d){var a=c.toLowerCase().indexOf(d.toLowerCase()),b;if(-1===a)return-1;if(0===a)return 0;b=c[a-1];return" "===b||"\t"===b||b.match(e)?a:-1},splitStringForDisplay:function(c,d,a){return{bprefix:c.substr(0,d),prefix:c.substr(d,a),suffix:c.substr(d+a)}}}});f.$Nav.when("sx.iss.TimingProvider.instance","sx.iss.EventBus.instance",
"sx.iss.suggestionUtils").build("sx.iss.utils",function(e,c,d){return{timingProvider:e,eventBus:c,suggestionUtils:d}});f.$Nav.when("$").build("sx.iss.DomUtils",function(e){var c=/\+/g,d=/^\s+/;(function(){Array.prototype.indexOf||(Array.prototype.indexOf=function(a,b){var c=this.length>>>0,d=Number(b)||0,d=0>d?Math.ceil(d):Math.floor(d);for(0>d&&(d+=c);d<c;d++)if(d in this&&this[d]===a)return d;return-1})})();return{isHoveredClass:"is-hovered",getKeyword:function(a){return(a=a.val())?
a.replace(d,""):a},isElHoveredOver:function(a){return a.hasClass("is-hovered")},hoverOverEl:function(a){return a.addClass("is-hovered")},hoverOutEl:function(a){return a.removeClass("is-hovered")},isArray:function(a){return"[object Array]"===Object.prototype.toString.call(a)},getFormParams:function(a){a=a.split("?");for(var b=1<a.length?a[1]:r,b=b?b.split("&"):[],d=b.length,e;0<d--;)e=b[d].split("="),b[d]={name:e[0],value:e[1].replace(c," ")};return{uri:a[0],formParams:b}},suggestionClass:".s-suggestion",
hiddenInputValue:"frmDynamic",hiddenInputClass:".frmDynamic",areAnySuggestionsHoveredOver:function(a){return 0<a.find(".is-hovered").length},getCursorPosition:function(a){a=a.get(0);if("selectionStart"in a)return a.selectionStart;if(document.selection){a.focus();var b=document.selection.createRange(),c=b.text.length;b.moveStart("character",-a.value.length);return b.text.length-c}return-1}}});f.$Nav.build("sx.iss.DebugUtils",function(){function e(a){if(a&&0<a.length){a=a.substring(1).split("&");
for(var c=0;c<a.length;c++){var d=a[c].split("=");if("debug"===d[0]){for(var g in b)b.hasOwnProperty(g)&&(b[g]=-1!==d[1].indexOf(g)?!0:!1);break}}}}function c(){return b.iss||b.isstrace}function d(){return b.isstrace}function a(a,b){c()&&f.console&&(b!==r?console.debug(a,b):console.debug(a))}var b={iss:!1,isstrace:!1,noiss:!1,isspolyfill:!1,isscf:!1};e(f.location.search);return{init:e,logDebug:a,logDebugWithTrace:function(b,c){a(b,c);d()&&console.trace()},isDebugModeOn:c,isDebugModeOnWithTrace:d,
isDisableISS:function(){return b.noiss},isUsingPolyFill:function(){return b.isspolyfill},isQIAEnabled:function(){return b.isscf}}});f.$Nav.build("sx.iss.ObjectUtils",function(){return{freeze:function(e){Object.freeze&&e&&Object.freeze(e)}}});f.$Nav.when("$","sx.iss.DebugUtils").run(function(e,c){c.isDisableISS()||(e.fn.delegate&&!c.isUsingPolyFill()||e.extend(e.fn,{delegate:function(d,a,b){return this.bind(a,function(a){var h=e(a.target);if(h.is(d)||0<h.parents(d).length)return c.logDebug("delegate ",
{selector:d,target:h,event:a}),b.apply(h,arguments)})}}),f.$Nav.declare("sx.iss.DependenciesMet"))});f.$Nav.when("sx.iss.ObjectUtils").build("sx.iss.SuggestionTypes",function(e){var c={a9:{name:"a9",reftag:"i",templateId:"s-suggestion"},related:{name:"related",reftag:"i",templateId:"s-related-search"},a9Xcat:{name:"a9-xcat",reftag:"c",templateId:"s-suggestion"},a9XOnly:{name:"a9-xcat-only",reftag:"xo",source:"xo",templateId:"s-suggestion"},nextSearch:{name:"nextSearch",reftag:"nsis",
templateId:"s-nextSearch"},recentSearch:{name:"recentSearch",reftag:"rsis",templateId:"s-recentSearch"}};e.freeze(c);return c});f.$Nav.when("sx.iss.ObjectUtils").build("sx.iss.InfoTypes",function(e){var c={actor:"actor",author:"author",director:"director",seasonTitle:"season_title",title:"title"};e.freeze(c);return c});f.$Nav.build("sx.iss.DataAttributes",function(){return{fallback:{name:"isfb"},spellCorrected:{name:"issc"}}});f.$Nav.build("sx.iss.TimingEvents",
function(){return{latency:{group:"Latency",events:{timeToDisplay:"timeToDisplay"}}}});f.$Nav.when("sx.iss.DebugUtils").build("sx.iss.Events",function(e){function c(){var c=Date.now();return{uid:c,suggestionsReadyForDisplay:{name:"suggestionsReadyForDisplay-"+c},suggestionsReady:{name:"suggestionsReady-"+c},suggestionsRendered:{name:"suggestionsRendered-"+c},updateSearchBox:{name:"updateSearchBox-"+c},selectionChange:{name:"selectionChange-"+c},dropdownHidden:{name:"dropdownHidden-"+c},
updateSearchTerm:{name:"updateSearchTerm-"+c},suggestionClicked:{name:"suggestionClicked-"+c},suggestionsNeeded:{name:"suggestionsNeeded-"+c},relatedSearchesNeeded:{name:"relatedSearchesNeeded-"+c},a9RelatedSearchesNeeded:{name:"a9-relatedSearchesNeeded-"+c},relatedSearchesReady:{name:"relatedSearchesReady-"+c},a9SuggestionsNeeded:{name:"a9-suggestionsNeeded-"+c},recentSuggestionsNeeded:{name:"recent-suggestionsNeeded-"+c},noSuggestions:{name:"nosuggestions-"+c},searchBoxFocusIn:{name:"searchBoxFocusIn-"+
c},searchBoxFocusOut:{name:"searchBoxFocusOut-"+c},keydown:{name:"keydown-"+c},hideDropdown:{name:"hidedropdown-"+c},focusOnParent:{name:"focusOnParent-"+c},parentFocused:{name:"parentFocused-"+c},parentLostFocus:{name:"parentLostFocus-"+c},searchTermChanged:{name:"searchTermChanged-"+c},suggestionsDisplayed:{name:"suggestionsDisplayed-"+c},upArrowPressed:{name:"upArrowPressed-"+c},downArrowPressed:{name:"downArrowPressed-"+c},blockSearchBoxFocusInOnce:{name:"blockSearchBoxFocusInOnce-"+c},allowSearchBoxFocusIn:{name:"allowSearchBoxFocusIn-"+
c}}}return{globals:{issLoaded:{name:"issLoaded"},suggestionsRendered:{name:"suggestionsRendered"},initializeNavSearchBox:{name:"initializeSearchBox"},navConfigReady:{name:"navConfigReady"}},createInstance:function(){return new c},createEvent:function(c,a){var b=a;a.hasOwnProperty("name")?b=a.name:"string"===typeof a?b=a:e.logDebug('Format of "event" parameter is not a string or an event object',a);return c+"-"+b}}});f.$Nav.when("sx.iss.ObjectUtils").build("sx.iss.Platform",function(e){var c=
{name:"mobile",cid:"amazon-search-ui-mobile",callback:"String",needExtraParams:!1};e.freeze(c);return c});f.$Nav.when("$").build("sx.iss.TimingProvider.instance",function(e){return new function(){var c={};this.startTimer=function(d,a){c[d]||(c[d]={});c[d][a]={start:+new Date}};this.stopTimer=function(d,a){var b=c[d]&&c[d][a];if(!b)return-1;b.end=+new Date;return b.end-b.start};this.getTimings=function(d){return c[d]};this.getTimingStats=function(d){var a={name:d},b=0,m=0,h=r,f=r,g=0,k=0,q=[],n=0,
p=0;if(!c[d])return r;e.each(c[d],function(a,b){if(b.start&&b.end){k=b.end-b.start;q.push(k);g++;m+=k;if(!h||k<h)h=k;if(!f||k>f)f=k}});q.sort();a.n=g;a.avg=m/g;a.min=h;a.max=f;a.med=1===g?q[0]:g%2?(q[Math.floor(g/2)]+q[Math.ceil(g/2)])/2:q[g/2];for(b=0;b<g;b++)n=q[b]-a.avg,n*=n,p+=n;a.stddev=Math.sqrt(p/g);return a};this.getTimingWithDisplayLatency=function(d,a){var b=c[d]&&c[d][a];return b?b.end-b.start+100:-1}}});f.$Nav.when("$","sx.iss.utils","sx.iss.Events").build("sx.iss.A9SuggestionProvider",
function(e,c,d){return function(a,b){function m(a){var g=++k,e,m;p=document.getElementsByTagName("head").item(0);v="JscriptId"+g;t=document.createElement("script");t.setAttribute("type","text/javascript");t.setAttribute("charset","utf-8");t.setAttribute("src",n);t.setAttribute("id",v);t.onload=t.onreadystatechange=function(){if(!(e||this.readyState!==r&&"loaded"!==this.readyState&&"complete"!==this.readyState)){e=!0;m=h.call(l,a);this.onload=this.onreadystatechange=null;try{p.removeChild(t)}catch(k){}f.completion=
r;c.timingProvider.stopTimer("a9",g);var v=d.createEvent("a9",b.suggestionsReady);c.eventBus.trigger(v,{searchTerm:a,suggestions:m})}};c.timingProvider.startTimer("a9",g);p.appendChild(t)}function h(a){var b=f.completion[1],d=2<f.completion.length?f.completion[2]:[],e=[],h,k,m,l,v,n,q,t,p;m="aps"===document.getElementById("nav-search-keywords-data").getAttribute("data-implicit-alias");var z=!1;if(0<d.length&&d[0].nodes!==r&&!m&&g.issXCat){l=!1;for(h=0;h<d[0].nodes.length;h++)if("aps"===d[0].nodes[h].alias){l=
!0;break}l||d[0].nodes.unshift({alias:"aps",name:g.apsName})}else 0<d.length&&d[0].nodes===r&&!m&&g.issXCat&&(d[0].nodes=[{alias:"aps",name:g.apsName}]);0===b.length&&0<a.length&&!m&&g.issXCat&&(b=[a],d=[{nodes:[{alias:"aps",name:g.apsName}]}],z=!0);for(h=0;h<b.length;h++)if(m=b[h],l=encodeURIComponent(m),n=d&&d[h]&&"1"===d[h].sc,t=c.suggestionUtils.getPrefixPos(m,a),k=!1,g.issXCat&&d&&d[h]&&d[h].source&&d[h].source[0]&&(k="xo"===d[h].source[0]||"fb"===d[h].source[0]),n||-1===t?(t=m,p=q=""):(q=c.suggestionUtils.splitStringForDisplay(m,
t,a.length),t=q.bprefix,p=q.prefix,q=q.suffix),z||k||e.push({type:"a9",spellCor:n,bprefix:t,prefix:p,suffix:q,keyword:m,url:"/s?k="+l}),v=d[h].nodes||[],!g.noXcats||g.issXCat)for(k=0;k<v.length;k++)e.push({type:"a9",spellCor:n,bprefix:t,prefix:p,suffix:q,keyword:m,store:v[k].name,storeText:g.searchboxSearchInMessage+v[k].name,scope:v[k].alias,url:"/s?k="+l+"&i="+encodeURIComponent(v[k].alias)});return e||[]}var l=this,g=a||{},k=0,q,n,p,v,t;l.getName=function(){return"a9"};var z=d.createEvent("a9",
b.suggestionsNeeded);c.eventBus.listen(z,function(a){if((q=a)&&q.length){var h;h=g.aliases.split(",");var k=g.implicitAlias;a={};var l="";a.aliases=k?[k]:h;a.aliases&&1===a.aliases.length&&(a.alias=a.aliases[0]);h=a.alias||"aps";a=e.extend({},{cid:"amazon-search-ui-mobile",action:"",sugPrefix:"issDiv",callback:"String"},g);a.protocol=a.protocol||f.parent.document.location.protocol;k="&q="+encodeURIComponent(q)+"&search-alias="+h+"&client="+a.cid+"&mkt="+a.mkt+"&x="+a.callback;a.issPrimeEligible&&
-1!==e.inArray(h,a.issPrimeEligible)?l="&pf=1&fb=0":g.issXCat&&(l="&fb=1");(n=a.protocol+"//"+a.src+"?method=completion"+k+l)&&m.call(this,q)}else a=d.createEvent("a9",b.suggestionsReady),c.eventBus.trigger(a,{searchTerm:q,suggestions:[]})},l)}});f.$Nav.when("$","sx.iss.utils","sx.iss.Events").build("sx.iss.RecentSearchSuggestionProvider",function(e,c,d){return function(a){var b=/[^\w]/;this.getName=function(){return"recent"};var m=d.createEvent("recent",a.suggestionsNeeded);c.eventBus.listen(m,
function(h){var m=[];if(f.sx&&f.sx.searchsuggest&&f.sx.searchsuggest.searchedText){var g=f.sx.searchsuggest.searchedText,k={},q,n,p,v,t,z,u;u=h&&b.test(h)?e("<div></div>").text(h).html():h;for(v=0;v<g.length;v++)n=g[v].keywords,q=(q=n)&&b.test(q)?e("<div></div>").html(q).text():q,p=c.suggestionUtils.getPrefixPosMultiWord(n,u),k[n]||-1===c.suggestionUtils.getPrefixPosMultiWord(q,h)||(-1===p?(p=n,z=t=""):(t=c.suggestionUtils.splitStringForDisplay(n,p,u.length),p=t.bprefix,z=t.prefix,t=t.suffix),m.push({type:"recent",
spellCor:!1,bprefix:p,prefix:z,suffix:t,keyword:q,originalKeywords:n,deleteUrl:g[v].deleteUrl}),k[n]=1)}g=d.createEvent("recent",a.suggestionsReady);c.eventBus.trigger(g,{searchTerm:h,suggestions:m})},this)}});f.$Nav.when("$","sx.iss.utils","sx.iss.TemplateEngine").build("sx.iss.SuggestionDisplayProvider",function(e,c,d){return function(a,b,c){var h,f;this.getDisplay=function(a){if(!h(a))return r;e.extend(a,c);return f(a)};h="string"===typeof a?function(b){return b.type===a}:a;f=d(b)}});
f.$Nav.when("sx.iss.utils","sx.iss.TemplateEngine").build("sx.iss.IssDisplayProvider",function(e,c){return function(d,a,b,m){var h=c(d),f=0;e.eventBus.listen([m.parentFocused,m.searchTermChanged],function(a){e.eventBus.trigger(m.suggestionsNeeded,a)},this).listen(m.suggestionsReady,function(c){var d=function(a){var b={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;","/":"&#x2F;"};return String(a).replace(/[&<>"'\/]/g,function(a){return b[a]})}(c.searchTerm),q,n,p,v=f++;e.timingProvider.startTimer("IssDisplayProvider",
v);n=a.sequence(c);for(c=0;c<n.length;c++){n[c].suggestionId="issDiv"+c;for(q=0;q<b.length&&!(p=b[q].getDisplay(n[c]));q++);n[c].display=p;p=r}p=h({suggestions:n});e.timingProvider.stopTimer("IssDisplayProvider",v);e.eventBus.trigger(m.suggestionsReadyForDisplay,{searchTerm:d,display:p,suggestions:n})},this)}});f.$Nav.when("$","sx.iss.utils","sx.iss.Platform","sx.iss.DebugUtils").build("sx.iss.NavConfigProvider",function(e,c,d,a){return function(b){function m(){var a=(b.protocol||f.parent.document.location.protocol||
"http")+"//"+c.extractDomainFromUrl(b.src)+"/suggestions/nav_config/2017?client=amazon-search-ui&",g="";e.each({mkt:b.mkt,r:b.requestId,s:b.sessionId,c:b.customerId,p:b.pageType,l:b.language,sv:d.name},function(a,b){g+=a+"="+b+"&"});return a+g}function h(a){a&&e.extend(b,{weblabs:a.weblabTreatments});f.$Nav.publish("sx.iss.navready",b)}function l(a,b){var c="iss:nav_config:"+a;g&&g(c,(g(c)||0)+b)}var g=f.ue&&"function"===typeof f.ue.count&&f.ue.count,k="function"===typeof f.uet&&f.uet,q="function"===
typeof f.uex&&f.uex;(function(){"undefined"===typeof f.iss&&(f.iss={});l("ajax:init",1);k&&k("bb","navConfigAjax:success",{wb:1});k&&k("bb","navConfigAjax:failure",{wb:1});var c=m();a.logDebugWithTrace("Issuing Nav config requests");e.ajax({url:c,cache:!1,dataType:"json",timeout:2E3,success:function(b){k&&k("cf","navConfigAjax:success",{wb:1});l("ajax:success",1);h(b);a.logDebugWithTrace("Successfully retrieved Nav config");k&&k("be","navConfigAjax:success",{wb:1});q&&q("ld","navConfigAjax:success",
{wb:1})},error:function(c,g,d){k&&k("cf","navConfigAjax:failure",{wb:1});l("ajax:error",1);g&&l("ajax:error:"+g,1);f.ueLogError&&(f.ueLogError({logLevel:"WARN",attribution:"iss-nav-config",message:"ISS Nav config call failed with responseText: "+(c&&c.responseText)+", pageType: "+(b&&b.pageType)+", status: "+g+", error:"+d}),h(r),a.logDebugWithTrace("Failed to retrieve Nav config"),k&&k("be","navConfigAjax:failure",{wb:1}),q&&q("ld","navConfigAjax:failure",{wb:1}))}})})();return{getWeblabTreatment:function(a){return b&&
b.weblabs&&b.weblabs[a]?b.weblabs[a]:"C"}}}});f.$Nav.when("sx.iss.utils").build("sx.iss.A9SearchSuggestionEventHandler",function(e){return function(c){var d;this.getDelegateReqs=function(){return{selectors:".a9_suggestion,.suggestion_with_query_builder,.cross_category_suggestion",events:"click"}};this.handleEvent=function(a){var b=a.target||a.srcElement;a=parseInt(a.currentTarget.id.substr(6),10);b.className&&-1!==b.className.indexOf("suggest_builder")?e.eventBus.trigger(c.updateSearchTerm,
d.suggestions[a].keyword):e.eventBus.trigger(c.suggestionClicked,d.suggestions[a])};e.eventBus.listen(c.suggestionsDisplayed,function(a){d=a},this)}});f.$Nav.when("sx.iss.utils").build("sx.iss.RecentSearchSuggestionEventHandler",function(e){return function(c){function d(a){var b,d,g,k;b=location.protocol+"//"+location.host+a.deleteUrl;d=f.sx.searchsuggest.searchedText;for(g=0;g<d.length;g++)if(d[g].keywords===a.originalKeywords){k=g;break}-1!==k&&d.splice(k,1);e.eventBus.trigger(c.focusOnParent);
var q;f.XMLHttpRequest?q=new XMLHttpRequest:f.ActiveXObject&&(q=new ActiveXObject("Microsoft.XMLHTTP"));if(q&&b)try{q.open("GET",b,!0),q.send(null)}catch(n){}}var a=this,b;this.getDelegateReqs=function(){return{selectors:".recent_search_suggestion",events:"click"}};this.handleEvent=function(m){var h=m.target||m.srcElement;m=parseInt(m.currentTarget.id.substr(6),10);h.className&&-1!==h.className.indexOf("iss_sh_delete")?d.call(a,b.suggestions[m]):e.eventBus.trigger(c.suggestionClicked,b.suggestions[m])};
e.eventBus.listen(c.suggestionsDisplayed,function(a){b=a},this)}});f.$Nav.when("sx.iss.utils","sx.iss.Events").build("sx.iss.SuggestionAggregator",function(e,c){return function(d,a){function b(b){var c=m[b.searchTerm];if(b.suggestions&&b.suggestions[0]&&b.suggestions[0].type&&(c.suggestionsSets[b.suggestions[0].type]=b,"a9"===b.suggestions[0].type)){b=c.suggestionsSets.a9.suggestions;for(var d=0;d<b.length;d++)b[d].scope&&(b[d].type="a9xc")}--c.remaining||(delete m[c.searchTerm],e.eventBus.trigger(a.suggestionsReady,
c))}for(var m={},h=0;h<d.length;h++){var f=c.createEvent(d[h],a.suggestionsReady);e.eventBus.listen(f,b,this)}e.eventBus.listen(a.suggestionsNeeded,function(b){if(!m[b]){m[b]={remaining:d.length,searchTerm:b,suggestionsSets:{}};for(var h=0;h<d.length;h++){var f=c.createEvent(d[h],a.suggestionsNeeded);e.eventBus.trigger(f,b)}}},this)}});f.$Nav.when("sx.iss.utils").build("sx.iss.SuggestionSequencerMobile",function(e){return function(){this.sequence=function(c){var d=c.suggestionsSets,a=
d.recent;c=d.a9;var b=d.crossCategory,d=c&&c.suggestions&&0<c.suggestions.length?c.suggestions.length:0,e=b&&b.suggestions&&0<b.suggestions.length?b.suggestions.length:0,h=6,f,g=[],k={},h=Math.min(a&&a.suggestions&&0<a.suggestions.length?a.suggestions.length:0,0<d?2:6);for(f=0;f<e;f++)g.push(b.suggestions[f]);for(f=0;f<h;f++)k[a.suggestions[f].keyword]=!0,g.push(a.suggestions[f]);h=Math.min(d,6-g.length);for(a=f=0;f<d&&a<h;f++)k[c.suggestions[f].keyword]||(a++,g.push(c.suggestions[f]));for(f=0;f<
g.length;f++)g[f].dispIdx=f;return g}}});f.$Nav.when("$","sx.iss.utils","sx.iss.Events").build("sx.iss.IssParentCoordinatorMobile",function(e,c,d){return function(a,b,d,h,l){function g(a){return a.charCode?a.target.value+String.fromCharCode(a.charCode):a.target.value}function k(){}function q(){u&&(u.remove(),u=r)}function n(a,b){if(a&&0<a.length)a.attr("value",b.value);else if(b.hasOwnProperty("value")&&b.value){a=e("<input>");for(var c in b)b.hasOwnProperty(c)&&a.attr(c,b[c]);a.appendTo(w)}}
function p(){var a=document.getElementById("issprefix"),b=document.getElementById("issAlias");return u?(H=setTimeout(function(){H=null;q();a&&w[0].removeChild(a);b&&w[0].removeChild(b)},300),!1):!0}function v(){f.setTimeout(function(){a.focus()},0)}function t(a){if("focus"===a.type){z=!0;if(null==h.autoScroll||h.autoScroll){var b=x.offset();f.scrollTo(0,b.top)}H&&(clearTimeout(H),H=null);C=g(a);c.eventBus.trigger(l.parentFocused,C)}else"keyup"===a.type&&(13===a.keyCode?q():27===a.keyCode?p():(D=C=
g(a),c.eventBus.triggerThrottledEvent(l.searchTermChanged,C,100)))}var z,u,w,x,H=null,D,C,y=h.implicitAlias,E=h.issXCat,B=!1;x=e(a);a=e(a);b=b?e(b):a.parent();w=a.closest("form");d=d||[];D=a.val();a.bind("focus",this,t).bind("keyup",this,t);e(document).ready(function(){x.is(":focus")&&x.trigger("focus","norefresh")});e(document.body).bind("click",this,function(b){var g=e(b.target||b.srcElement),d=g.hasClass("suggest_builder"),g=g.hasClass("iss_sh_delete");"click"!==b.type||document.activeElement==
a[0]||g||d||(z=!1,c.eventBus.trigger(l.parentLostFocus),p())});e(document).bind("searchAjaxTransition",this,q);f.setInterval(function(){var b=a.val();b!==C&&(C=D=b,c.eventBus.triggerThrottledEvent(l.searchTermChanged,C,100))},20);c.eventBus.listen(l.suggestionsReadyForDisplay,function(a){var g,h;if(z&&a&&C===a.searchTerm.replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&#x2F;/g,"/"))if(a.suggestions&&0!==a.suggestions.length){g=
e(a.display);E&&!B&&(B=!0,ue.count("SEARCH:IssXCatImpression",1));if(u)u.html(g.children());else for(u=g,b.after(u),g=0;g<d.length;g++)h=d[g].getDelegateReqs(),u.delegate(h.selectors,h.events,d[g],function(a){return a.data.handleEvent(a)});e(f).resize(k);c.eventBus.trigger(l.suggestionsDisplayed,a)}else q()},this).listen(l.suggestionClicked,function(b){var c;a.val(b.keyword);C=b.keyword;var g;c=D;var d=b.dispIdx;if(0<=d){b.spellCor?g="ss_sc":"recent"===b.type?g="ss_sh":E?"a9xc"===b.type?g="aps"===
b.scope?"ss_c_aw_aps":"ss_c_aw_cat":(b.scope=y,g="ss_i"):g="crossCategory"===b.type?"aps"===b.scope?"ss_c_aw_aps":"ss_c_aw_cat":"ss_i";E&&"a9xc"===b.type?ue.count("SEARCH:IssXCatClick",1):E&&ue.count("SEARCH:IssTopCatClick",1);if(E){var h=b.scope?b.scope:y,k;"a9xc"===b.type&&E&&((k=e("input[name='n']"))&&0<k.length&&n(k,{value:"",name:"n",type:"hidden"}),(k=e("input[name='bbn']"))&&0<k.length&&n(k,{value:"",name:"bbn",type:"hidden"}),(k=e("input[name='srs']"))&&0<k.length&&n(k,{value:"",name:"srs",
type:"hidden"}));n(e("#issAlias"),{value:"i:"+h,name:"rh",type:"hidden"});(k=e("input[name='search-alias']"))&&0<k.length&&n(k,{value:h,name:"search-alias",type:"hidden"});k=e("input[name='n']");"aps"===h&&k&&0<k.length&&n(k,{value:"",name:"n",type:"hidden"});k=e("input[name='srs']");"aps"===h&&k&&0<k.length&&n(k,{value:"",name:"srs",type:"hidden"});k=e("input[name='bbn']");"aps"===h&&k&&0<k.length&&n(k,{value:"",name:"bbn",type:"hidden"})}h="";E&&b.scope&&(h=b.scope);b=g;g=c.length;k=w[0].getAttribute("action");
var f=/(ref=[\w-]+)/,d=b+"_"+d+"_"+g;h&&0<h.length&&(d=d+"_"+h);f.test(k)?k=k.replace(f,"ref=is_s_"+d):("/"!=k.charAt(k.length-1)&&(k+="/"),k+="ref=is_s_"+d);w[0].setAttribute("action",k);n(e("#issprefix"),{value:c,name:"sprefix",type:"hidden"})}if(document.createEvent&&(c=document.createEvent("Event"),c.initEvent("submit",!0,!0),!w[0].dispatchEvent(c)))return;w[0].submit()},this).listen(l.focusOnParent,v,this).listen(l.updateSearchTerm,function(a){C=a;x.val(a);v()},this)}});f.$Nav.importEvent("jQuery",
{as:"$",global:"jQuery"});f.$Nav.when("sx.iss.Events","sx.iss.A9SuggestionProvider","sx.iss.A9SearchSuggestionEventHandler","sx.iss.RecentSearchSuggestionProvider","sx.iss.RecentSearchSuggestionEventHandler","sx.iss.SuggestionAggregator","sx.iss.SuggestionSequencerMobile","sx.iss.SuggestionDisplayProvider","sx.iss.IssDisplayProvider","sx.iss.IssParentCoordinatorMobile").build("sx.iss",function(e,c,d,a,b,f,h,l,g,k){return{Events:e,A9SuggestionProvider:c,A9SearchSuggestionEventHandler:d,RecentSearchSuggestionProvider:a,
RecentSearchSuggestionEventHandler:b,SuggestionAggregator:f,SuggestionSequencerMobile:h,SuggestionDisplayProvider:l,IssDisplayProvider:g,IssParentCoordinatorMobile:k}});f.$Nav.when("sx.iss").run(function(e){f.$Nav.publish("sx.iss",e)});f.$Nav.when("$","sx.iss.SuggestionTypes").build("sx.iss.FilterIss",function(e,c){return function(d){return{removeFilteredAliases:function(a){d.filterAliases&&a[c.a9Xcat.name]&&(a[c.a9Xcat.name]=e.grep(a[c.a9Xcat.name],function(a){return-1===e.inArray(a.alias,
d.filterAliases)}));return a}}}})});